import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier # <-- NEW IMPORT
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
import shap

#============ DATA PREPROCESSING ============#

# Assuming your dataframe is already loaded as 'df'
df = pd.read_csv('European_Bank.csv')
# Keep a copy of the original data for reference
df_org = df.copy()

# 1. Check and Handle missing values 
# Count missing values in every column
missing_counts = df.isnull().sum()
total_missing = missing_counts.sum()

print(f"Total missing values found: {total_missing}")

# If we find any missing values, we trigger the fill logic
if total_missing > 0:
    # Print out specifically which columns are missing data
    print("Columns with missing values:\n", missing_counts[missing_counts > 0])
    
    # Fill missing numbers with the median (middle value)
    df.fillna(df.median(numeric_only=True), inplace=True) 
    # Fill any remaining missing text/categorical values with 'Unknown'
    df.fillna('Unknown', inplace=True) 
    
    print("Missing values have been successfully filled.")
else:
    print("No missing values detected. Your dataset is clean, skipping the fill step!")

# 2. Remove non-informative features [cite: 4]
# We drop columns that don't help predict churn.
df = df.drop(['CustomerId', 'Surname'], axis=1) 

# 3. Encode categorical variables using One-hot encoding [cite: 5, 6]
# Machine learning models only understand numbers, so we convert text into binary (0 or 1) columns.
df = pd.get_dummies(df, columns=['Geography', 'Gender'], drop_first=True) 
# Note: We will scale the numerical features AFTER the train-test split to prevent "data leakage" [cite: 7]

#============ FEATURE ENGINEERING ============#

# (Optional) You can keep your geographic interaction if you found it useful during EDA!
# Assuming Gender_Male was generated by drop_first=True
# df['Male_Germany'] = df['Gender_Male'] * df['Geography_Germany']

# 1. Balance-to-Salary ratio 
# How much money they have stored compared to their salary.
df['Balance_to_Salary'] = df['Balance'] / df['EstimatedSalary'] 

# 2. Product density indicator 
# Products per year of tenure. We add 0.01 to Tenure to avoid dividing by zero!
df['Product_Density'] = df['NumOfProducts'] / (df['Tenure'] + 0.01) 

# 3. Engagement-product interaction 
# Combines their active status with the number of products they hold.
df['Engagement_Product'] = df['IsActiveMember'] * df['NumOfProducts'] 

# 4. Age-tenure interaction features 
# Combines age and how long they've been with the bank.
df['Age_Tenure'] = df['Age'] * df['Tenure']

#============ PREPARE DATA FOR MODELING (Train-Test Split) ============#

# Define the Predictive Target Variable
# X contains the features (inputs), y contains the target (output)
X = df.drop('Exited', axis=1)
y = df['Exited'] # 1 -> Customer churned, 0 -> Customer retained 

# Train-Test Split
# We split the data: 80% for training (learning), 20% for testing (evaluating)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.2, 
    random_state=42, 
    stratify=y # This preserves the churn class distribution
)

# NOW we scale our numerical features
scaler = StandardScaler()
# We learn the scale from the training data, and apply it to both train and test data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#============ MODEL TRAINING ============#

# 0. Simple Baseline: K-Nearest Neighbors (KNN)
# We set n_neighbors=5, meaning it looks at the 5 most similar customers.
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled, y_train)

# 1. Regression Model
# Logistic Regression acts as our simple interpretability benchmark.
log_reg = LogisticRegression()
log_reg.fit(X_train_scaled, y_train)

# 2. Tree-Based Models
# Decision Tree and Random Forest
tree = DecisionTreeClassifier(random_state=42)
tree.fit(X_train_scaled, y_train)

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train_scaled, y_train)

# 3. Advanced Models
# Gradient Boosting
gb = GradientBoostingClassifier(random_state=42)
gb.fit(X_train_scaled, y_train)

#============ MODEL EVALUATION ============#

models = {
    "KNN (Simple Baseline)": knn,
    "Logistic Regression (Interpretability Baseline)": log_reg,
    "Decision Tree": tree,
    "Random Forest": rf,
    "Gradient Boosting": gb
}

best_model_name = ""
best_model = None
best_accuracy = 0.0

print("\n" + "="*40)
print("MODEL EVALUATION & SELECTION")
print("="*40)

for name, model in models.items():
    y_pred = model.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    
    print(f"\n--- {name} ---")
    print(f"Accuracy: {acc:.4f}")
    print(f"Confusion Matrix:\n{cm}")
    
    if acc > best_accuracy:
        best_accuracy = acc
        best_model_name = name
        best_model = model

print("\n" + "="*40)
print(f"🏆 BEST MODEL SELECTED: {best_model_name} (Accuracy: {best_accuracy:.4f})")
print("="*40)

# Calculate full metrics for the BEST model
y_pred_best = best_model.predict(X_test_scaled)
y_prob_best = best_model.predict_proba(X_test_scaled)[:, 1] 

print(f"\nDetailed Metrics for {best_model_name}:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_best):.3f}")
print(f"Precision: {precision_score(y_test, y_pred_best):.3f}")
print(f"Recall: {recall_score(y_test, y_pred_best):.3f}")
print(f"F1-Score: {f1_score(y_test, y_pred_best):.3f}")
print(f"ROC-AUC: {roc_auc_score(y_test, y_prob_best):.3f}")

#============ MODEL INTERPRETABILITY ============#

# 1. Feature Importance (Built into Random Forest)
importances = pd.Series(rf.feature_importances_, index=X.columns).sort_values(ascending=False)
print("\nTop 5 Feature Importances (Random Forest):")
print(importances.head(5))

# 2. SHAP Value Analysis
explainer = shap.TreeExplainer(rf)
shap_values = explainer.shap_values(X_test_scaled)

# Dynamically check the shape of the SHAP values to prevent version errors
if isinstance(shap_values, list):
    # For older SHAP versions
    shap_values_to_plot = shap_values[1]
elif len(shap_values.shape) == 3:
    # For newer SHAP versions: slice all rows, all columns, class index 1 (Churn)
    shap_values_to_plot = shap_values[:, :, 1]
else:
    # Fallback
    shap_values_to_plot = shap_values

# Plot the summary, using X_test (unscaled) so the x-axis shows real, readable numbers!
shap.summary_plot(shap_values_to_plot, X_test, feature_names=X.columns)
print(df.head())
df.head()


